source 'https://rubygems.org'

gem "ffi", force_ruby_platform: true
gem "jekyll", "~> 4.4.1"
gem "jekyll-feed", "~> 0.17"
gem "kramdown-parser-gfm", "~> 1.1"
gem "rouge", "~> 4.2"
gem 'jekyll-gfm-admonitions', '~> 1.2'
