source 'https://rubygems.org'

gem "ffi", force_ruby_platform: true
gem "jekyll", "~> 4.4.1"
gem "jekyll-feed", "~> 0.17"
gem "kramdown-parser-gfm", "~> 1.1"
gem "rouge", "~> 4.7"
gem 'jekyll-gfm-admonitions', '~> 1.2'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jekyll-last-modified-at', '~> 1.3', '>= 1.3.2'
